jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Download Python 3.13
        uses: actions/download-artifact@v2
        with:
          name: python-3.13.0.amd64
          path: /tmp/python-3.13.0.amd64.exe

      - name: Extract Python 3.13
        run: |
          gunzip /tmp/python-3.13.0.amd64.exe
          tar -xf /tmp/python-3.13.0.amd64

      - name: Add Python 3.13 to PATH
        run: echo "**/python313/bin" >> $GITHUB_PATH

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Set Hugging Face Token
        run: echo "HUGGINGFACE_TOKEN=${{ secrets.HUGGINGFACE_TOKEN }}" >> $GITHUB_ENV

      - name: Run Streamlit App
        run: |
          streamlit run app.py
